services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: run-short-node:test
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    working_dir: /app
    command: ['npx', 'vitest', '--watch']
    tty: true
    environment:
      - NODE_ENV=testing
      - IS_DOCKER=true
